import { api, ApiError } from '@/services/api/client';
import type { MealType } from '@/types';

/**
 * Planning service — the weekly meal plan and the monthly supplement regimen.
 *
 * Both are generated by the model on the server, so neither is available the
 * moment it is asked for. The shape of that is identical for the two: a
 * `generate` call that returns an id, a status that walks
 * `idle → generating → ready | failed`, and a fetch for the finished artefact.
 * {@link awaitPlan} is the one place that loop is written, so a screen only ever
 * deals in "here is the plan" or "here is why there isn't one".
 */

export type GenerationStatus = 'idle' | 'generating' | 'ready' | 'failed';

// ── Meal plans ──────────────────────────────────────────────────────────────

/**
 * Whether a meal's figures were measured or estimated.
 *
 * `estimated` is the planner's own arithmetic for a dish nobody weighed;
 * `verified` means the dish was matched to a published recipe and the numbers
 * are that recipe's panel, scaled to this portion. The screens label the two
 * differently — a guess is never shown as a measurement.
 */
export type NutritionSource = 'estimated' | 'verified';

/**
 * The measured extras behind a dish, per serving.
 *
 * Only present on a verified meal, and every field is independently nullable:
 * a published recipe reports what it reports, and a null here means "not
 * known" rather than "none".
 */
export interface MealNutritionFacts {
  /** Grams. */
  saturatedFat: number | null;
  /** Grams. */
  sugar: number | null;
  sodiumMg: number | null;
  cholesterolMg: number | null;
  potassiumMg: number | null;
}

/** Where a dish's photograph, figures or method were published. */
export interface MealSource {
  name: string;
  url: string | null;
}

export interface PlannedMeal {
  id: string;
  /** ISO weekday the meal belongs to: 1 = Monday … 7 = Sunday. */
  dayOfWeek: number;
  mealType: MealType;
  /**
   * When to eat it, as local 24-hour "HH:MM". Null on plans generated before
   * meals were timed, which the screens render as a meal with no time rather
   * than inventing one.
   */
  scheduledTime: string | null;
  name: string;
  kcal: number;
  protein: number;
  carbs: number;
  fat: number;
  fiber: number;
  /** Whether the five figures above were measured or estimated. */
  nutritionSource: NutritionSource;
  /** Saturated fat, sugar, sodium and the rest. Null unless verified. */
  facts: MealNutritionFacts | null;
  /** Why this dish suits the user's goal — the "Why this fits your goal" card. */
  reasoning: string;
  /** Photograph of the dish, or null when none is attached yet. */
  imageUrl: string | null;
  /** Who published the dish this was matched to. Null when nothing matched. */
  source: MealSource | null;
}

export interface MealPlanTotals {
  kcal: number;
  protein: number;
  carbs: number;
  fat: number;
  fiber: number;
}

export interface MealPlanDay {
  dayOfWeek: number;
  /** Calendar date this day falls on (YYYY-MM-DD). */
  date: string;
  /** Full weekday name, e.g. "Monday". */
  dayName: string;
  totals: MealPlanTotals;
  meals: PlannedMeal[];
}

export interface MealPlanStatus {
  mealPlanId: string;
  status: GenerationStatus;
  error: string | null;
}

export interface MealPlan extends MealPlanStatus {
  weekStartDate: string;
  calorieTarget: number;
  /** Seven entries once ready; empty while generating. */
  days: MealPlanDay[];
  createdAt: string;
  updatedAt: string;
}

/** Asks the server to build this week's plan. Returns an id to poll. */
export async function generateMealPlan(): Promise<MealPlanStatus> {
  return api.post<MealPlanStatus>('/api/v1/meal-plans/generate');
}

/** This week's plan, or null when the week has none yet. */
export async function getCurrentMealPlan(): Promise<MealPlan | null> {
  return orNull(api.get<MealPlan>('/api/v1/meal-plans/current'));
}

export async function getMealPlan(mealPlanId: string): Promise<MealPlan> {
  return api.get<MealPlan>(`/api/v1/meal-plans/${mealPlanId}`);
}

export async function getMealPlanStatus(mealPlanId: string): Promise<MealPlanStatus> {
  return api.get<MealPlanStatus>(`/api/v1/meal-plans/${mealPlanId}/status`);
}

/** One meal from a plan — the detail screen's own source of truth. */
export async function getPlannedMeal(
  mealPlanId: string,
  mealId: string,
): Promise<PlannedMeal> {
  return api.get<PlannedMeal>(`/api/v1/meal-plans/${mealPlanId}/items/${mealId}`);
}

/**
 * Exchanges one meal for a different dish of equivalent nutrition.
 *
 * Generation happens inline on the server, so this resolves with the
 * replacement rather than an id to poll — the user is waiting on one dish, not
 * a week.
 */
export async function swapPlannedMeal(
  mealPlanId: string,
  mealId: string,
): Promise<PlannedMeal> {
  return api.post<PlannedMeal>(`/api/v1/meal-plans/${mealPlanId}/items/${mealId}/swap`, undefined, {
    // A swap runs a model call; the default read timeout is not enough room.
    timeoutMs: 45_000,
  });
}

// ── Recipes ─────────────────────────────────────────────────────────────────

export type RecipeDifficulty = 'easy' | 'medium' | 'hard';

/** One line of a recipe's shopping list. */
export interface RecipeIngredient {
  /** The ingredient itself, e.g. "Chicken breast". */
  name: string;
  /** How much the whole recipe needs, e.g. "200 g". */
  quantity: string;
  /** Preparation done before cooking, e.g. "finely diced". Null when none. */
  note: string | null;
}

/** One numbered step of a method. */
export interface RecipeStep {
  /** 1-based position, supplied by the server so the client never derives it. */
  number: number;
  /** What the step achieves, e.g. "Sear the chicken". */
  title: string;
  instruction: string;
  /** Roughly how long it takes. Null when the step is instant. */
  minutes: number | null;
}

/**
 * How to cook one planned meal.
 *
 * Carries the dish as well as the method — its name, photograph and nutrition —
 * so the recipe screen renders whole from this one response rather than
 * depending on params the caller happened to be holding.
 */
export interface MealRecipe {
  mealId: string;
  name: string;
  mealType: MealType;
  imageUrl: string | null;

  /** Nutrition of one portion, exactly as the plan counted it. */
  kcal: number;
  protein: number;
  carbs: number;
  fat: number;
  fiber: number;

  summary: string;
  cuisine: string;
  difficulty: RecipeDifficulty;
  servings: number;
  prepMinutes: number;
  cookMinutes: number;
  /** Prep plus cook, summed on the server so every surface agrees. */
  totalMinutes: number;

  ingredients: RecipeIngredient[];
  steps: RecipeStep[];
  tips: string[];

  /**
   * Who published this method. Null when it was written for this plan rather
   * than taken from a real recipe — which is exactly the difference the credit
   * line on the screen exists to show.
   */
  source: MealSource | null;
}

/**
 * The recipe for one planned meal.
 *
 * A POST because the first request for a dish writes it: the server generates
 * the method once and serves that same row from then on. Sending it as a GET
 * would let this client's automatic retry turn one slow response into several
 * paid generations.
 */
export async function getMealRecipe(
  mealPlanId: string,
  mealId: string,
): Promise<MealRecipe> {
  return api.post<MealRecipe>(
    `/api/v1/meal-plans/${mealPlanId}/items/${mealId}/recipe`,
    undefined,
    {
      // The first call for a dish runs a model generation; the default read
      // timeout would abandon it just as it lands.
      timeoutMs: 45_000,
    },
  );
}

// ── Supplement plans ────────────────────────────────────────────────────────

export type SupplementTier = 'core' | 'optional';

export type SupplementTime =
  | 'morning'
  | 'afternoon'
  | 'evening'
  | 'withMeal'
  | 'preWorkout'
  | 'postWorkout'
  | 'beforeBed';

/** One line of a supplement facts panel: what is in a serving, and how much. */
export interface SupplementIngredient {
  /** The compound, as a label names it, e.g. "Vitamin D3 (cholecalciferol)". */
  name: string;
  /** How much of it is in one serving, e.g. "1000 IU", "25 g". */
  amount: string;
}

export interface PlannedSupplement {
  id: string;
  name: string;
  tier: SupplementTier;
  /** What kind of supplement this is, e.g. "Protein supplement". */
  category: string;
  /** The single benefit it is taken for, e.g. "Muscle recovery & growth". */
  headline: string;
  bestTime: SupplementTime;
  /** Ready-made timing label, e.g. "Post-workout". */
  bestTimeLabel: string;
  /** What one serving is, e.g. "1 scoop (30 g)". */
  servingSize: string;
  /** The facts panel: every compound in a serving, with its amount. */
  ingredients: SupplementIngredient[];
  purpose: string;
  /**
   * The closing advice: see a healthcare provider and agree an amount before
   * starting. Always carries the standing disclaimer, so the screen never has to
   * add one of its own.
   */
  recommendation: string;
  benefits: string[];
  safety: string[];
  /** Product identity. Null unless a real catalogue backs this item. */
  brand: string | null;
  rating: number | null;
  ratingCount: number | null;
  imageUrl: string | null;
}

export interface SupplementScheduleGroup {
  bestTime: SupplementTime;
  label: string;
  items: PlannedSupplement[];
}

export interface SupplementPlanStatus {
  supplementPlanId: string;
  status: GenerationStatus;
  error: string | null;
}

export interface SupplementPlan extends SupplementPlanStatus {
  monthStartDate: string;
  /** Month the plan covers, ready to render: "July 2025". */
  monthLabel: string;
  items: PlannedSupplement[];
  schedule: SupplementScheduleGroup[];
  counts: { all: number; core: number; optional: number };
  createdAt: string;
  updatedAt: string;
}

/**
 * Ensures this month has a regimen. Idempotent: called again within the same
 * month it returns the existing plan and generates nothing further.
 */
export async function generateSupplementPlan(): Promise<SupplementPlanStatus> {
  return api.post<SupplementPlanStatus>('/api/v1/supplement-plans/generate');
}

/** This month's regimen, or null when the month has none yet. */
export async function getCurrentSupplementPlan(): Promise<SupplementPlan | null> {
  return orNull(api.get<SupplementPlan>('/api/v1/supplement-plans/current'));
}

export async function getSupplementPlan(planId: string): Promise<SupplementPlan> {
  return api.get<SupplementPlan>(`/api/v1/supplement-plans/${planId}`);
}

export async function getSupplementPlanStatus(planId: string): Promise<SupplementPlanStatus> {
  return api.get<SupplementPlanStatus>(`/api/v1/supplement-plans/${planId}/status`);
}

/** One supplement from a plan — the detail screen's own source of truth. */
export async function getPlannedSupplement(
  planId: string,
  itemId: string,
): Promise<PlannedSupplement> {
  return api.get<PlannedSupplement>(`/api/v1/supplement-plans/${planId}/items/${itemId}`);
}

// ── Polling ─────────────────────────────────────────────────────────────────

/** Gap between status checks. Generation takes tens of seconds, not milliseconds. */
const POLL_INTERVAL_MS = 2_000;

/**
 * How long to keep asking before giving up.
 *
 * Generous, because the cost of stopping early is worse than the cost of
 * waiting: the plan is still being written server-side either way, and a client
 * that gave up at thirty seconds would report a failure for work that succeeds a
 * moment later.
 */
const POLL_TIMEOUT_MS = 180_000;

/** Raised when generation finished unsuccessfully, carrying the server's reason. */
export class PlanGenerationError extends Error {
  constructor(message: string) {
    super(message);
    this.name = 'PlanGenerationError';
  }
}

/**
 * Polls a generation to completion.
 *
 * Transient read failures are swallowed rather than aborting the wait — a
 * dropped poll says nothing about the job, and the next tick will ask again. A
 * `failed` status is different: that is the server reporting the work is over,
 * so it throws with whatever reason it gave.
 *
 * @param readStatus Fetches the current status.
 * @param signal     Abandons the wait when the caller goes away.
 */
export async function awaitPlan(
  readStatus: () => Promise<{ status: GenerationStatus; error: string | null }>,
  signal?: AbortSignal,
): Promise<void> {
  const deadline = Date.now() + POLL_TIMEOUT_MS;

  for (;;) {
    if (signal?.aborted) throw abortError();

    try {
      const { status, error } = await readStatus();
      if (status === 'ready') return;
      if (status === 'failed') {
        throw new PlanGenerationError(
          error ?? 'Your plan could not be generated. Please try again.',
        );
      }
    } catch (caught) {
      if (caught instanceof PlanGenerationError) throw caught;
      // A poll that could not be read tells us nothing; keep waiting. Anything
      // the server rejects outright (a 404 for a plan that is not there, a 401)
      // is final and must not be retried until the deadline.
      if (caught instanceof ApiError && caught.status >= 400 && caught.status < 500) {
        throw caught;
      }
    }

    if (Date.now() >= deadline) {
      throw new PlanGenerationError(
        'Your plan is taking longer than usual. It will be ready shortly — pull to refresh.',
      );
    }

    await sleep(POLL_INTERVAL_MS, signal);
  }
}

function abortError(): Error {
  const error = new Error('Aborted');
  error.name = 'AbortError';
  return error;
}

function sleep(ms: number, signal?: AbortSignal): Promise<void> {
  return new Promise((resolve, reject) => {
    const timer = setTimeout(() => {
      signal?.removeEventListener('abort', onAbort);
      resolve();
    }, ms);

    function onAbort() {
      clearTimeout(timer);
      reject(abortError());
    }

    signal?.addEventListener('abort', onAbort);
  });
}

/**
 * Turns "this does not exist yet" into a value rather than an error.
 *
 * A user who has never generated a plan is not an error case, and every caller
 * of `current` would otherwise have to unpick a 404 from a real failure.
 */
async function orNull<T>(request: Promise<T>): Promise<T | null> {
  try {
    return await request;
  } catch (error) {
    if (error instanceof ApiError && error.status === 404) return null;
    throw error;
  }
}
