import {
  createContext,
  useCallback,
  useContext,
  useEffect,
  useMemo,
  useRef,
  useState,
  type ReactNode,
} from 'react';

import { ApiError } from '@/services/api/client';
import { isAuthenticated, loadSession } from '@/services/auth/session';
import { planningService } from '@/services';
import type { MealPlan, SupplementPlan } from '@/services/planning/planningService';

/**
 * VITAL AI — Plan generation state.
 *
 * Meal and supplement plans are generated by the model on the server: the user
 * taps "Generate", a worker builds the plan from their profile, and the client
 * polls until it is ready. That is a long-running, cross-screen operation — the
 * Planning tab shows its progress, two detail screens render its result, and
 * navigating between them must not restart it — so it is held here rather than
 * in any one screen.
 *
 * The plan itself lives here too, not just its status. Both plans are read far
 * more often than they change (a week's meals change weekly at most), and
 * keeping one copy means opening a meal and coming back is instant rather than
 * a fresh round trip.
 */

export type PlanStatus = 'idle' | 'generating' | 'ready' | 'failed';
export type PlanKind = 'meal' | 'supplement';

interface PlanState<T> {
  status: PlanStatus;
  /** The plan, once one has been read. Null while idle, generating or failed. */
  data: T | null;
  /** Why the last attempt failed, ready to show. */
  error: string | null;
}

interface PlanContextValue {
  meal: PlanState<MealPlan>;
  supplement: PlanState<SupplementPlan>;
  /** True until the first read of both plans has settled. */
  hydrating: boolean;
  /** Requests a plan and waits for it. Safe to call while one is in flight. */
  generate: (kind: PlanKind) => Promise<void>;
  /** Re-reads a plan already generated, without asking for a new one. */
  refresh: (kind: PlanKind) => Promise<void>;
  /**
   * Discards the held plan, so the user is offered a fresh one.
   *
   * Called when the inputs a plan was built from change — a new goal, a newly
   * declared health condition. The plan on the server is not deleted: it is
   * still an accurate record of what was suggested, and it is replaced only if
   * the user actually asks for a new one.
   */
  reset: (kind: PlanKind) => void;
  /** Replaces the held meal plan — used after a swap changes one meal. */
  applyMealPlan: (plan: MealPlan) => void;
}

const IDLE = { status: 'idle', data: null, error: null } as const;

const PlanContext = createContext<PlanContextValue | null>(null);

/** Turns anything thrown by the service into a line the user can read. */
function messageOf(error: unknown): string {
  if (error instanceof ApiError) return error.message;
  if (error instanceof Error) return error.message;
  return 'Something went wrong. Please try again.';
}

export function PlanProvider({ children }: { children: ReactNode }) {
  const [meal, setMeal] = useState<PlanState<MealPlan>>(IDLE);
  const [supplement, setSupplement] = useState<PlanState<SupplementPlan>>(IDLE);
  // The provider sits above the navigator, so it mounts before sign-in. Starting
  // in the hydrating state only when there is already a session means the very
  // first render is correct for both cases without an effect correcting it a
  // frame later.
  const [hydrating, setHydrating] = useState(() => isAuthenticated());

  // One generation per kind at a time. The controller aborts the poll loop when
  // the provider unmounts, so a signed-out user's app is not left waiting on a
  // plan nobody is going to look at.
  const polling = useRef<Record<PlanKind, AbortController | null>>({
    meal: null,
    supplement: null,
  });
  const mounted = useRef(true);

  useEffect(() => {
    mounted.current = true;
    // The record itself never changes identity, only its slots do — captured
    // here so the cleanup aborts whatever is in flight at unmount rather than
    // whatever was there when the effect ran.
    const inFlight = polling.current;

    return () => {
      mounted.current = false;
      Object.values(inFlight).forEach((controller) => controller?.abort());
    };
  }, []);

  /** Stores a freshly read plan of either kind. */
  const store = useCallback((kind: PlanKind, plan: MealPlan | SupplementPlan) => {
    if (!mounted.current) return;
    if (kind === 'meal') setMeal(stateOf(plan as MealPlan));
    else setSupplement(stateOf(plan as SupplementPlan));
  }, []);

  /**
   * Moves one plan to a new phase without touching the plan it already holds.
   *
   * The two plans are separate pieces of state of different types, and every
   * status change applies to whichever one the caller names — writing this once,
   * generically, is what keeps `generate` from having to fork on kind at each of
   * the four places it reports progress.
   */
  const setPhase = useCallback(
    (
      kind: PlanKind,
      phase: (current: { status: PlanStatus; data: unknown; error: string | null }) => {
        status: PlanStatus;
        error: string | null;
      },
    ) => {
      const apply = <T,>(current: PlanState<T>): PlanState<T> => ({ ...current, ...phase(current) });
      if (kind === 'meal') setMeal(apply);
      else setSupplement(apply);
    },
    [],
  );

  /**
   * Waits for a generation already under way and stores the result.
   *
   * Shared by `generate` and by hydration, which is what lets a plan caught
   * mid-generation — the user backgrounded the app while it built — be resumed
   * rather than restarted or, worse, left showing a spinner that never resolves.
   */
  const watch = useCallback(
    async (kind: PlanKind, planId: string, alreadyReady: boolean) => {
      if (polling.current[kind]) return;

      setPhase(kind, () => ({ status: 'generating', error: null }));

      const controller = new AbortController();
      polling.current[kind] = controller;

      try {
        if (!alreadyReady) {
          await planningService.awaitPlan(
            () =>
              kind === 'meal'
                ? planningService.getMealPlanStatus(planId)
                : planningService.getSupplementPlanStatus(planId),
            controller.signal,
          );
        }

        store(
          kind,
          kind === 'meal'
            ? await planningService.getMealPlan(planId)
            : await planningService.getSupplementPlan(planId),
        );
      } catch (error) {
        if (error instanceof Error && error.name === 'AbortError') return;
        if (!mounted.current) return;
        setPhase(kind, (current) => ({
          status: current.data ? 'ready' : 'failed',
          error: messageOf(error),
        }));
      } finally {
        if (polling.current[kind] === controller) {
          polling.current[kind] = null;
        }
      }
    },
    [store, setPhase],
  );

  /**
   * Reads whatever the server already has, on app start.
   *
   * A returning user has a plan; showing them a "Generate" button would invite
   * them to spend a model call replacing something they already own.
   */
  useEffect(() => {
    let active = true;

    void (async () => {
      // The persisted session is restored asynchronously at app start. Waiting
      // on it here is what stops a returning user's plans being read without a
      // token and coming back as a 401 they would have to pull-to-refresh past.
      const session = await loadSession();
      if (!active) return;

      if (!session) {
        setHydrating(false);
        return;
      }

      const [mealResult, supplementResult] = await Promise.allSettled([
        planningService.getCurrentMealPlan(),
        planningService.getCurrentSupplementPlan(),
      ]);

      if (!active) return;

      if (mealResult.status === 'fulfilled' && mealResult.value) {
        const plan = mealResult.value;
        setMeal(stateOf(plan));
        if (plan.status === 'idle' || plan.status === 'generating') {
          void watch('meal', plan.mealPlanId, false);
        }
      }
      if (supplementResult.status === 'fulfilled' && supplementResult.value) {
        const plan = supplementResult.value;
        setSupplement(stateOf(plan));
        if (plan.status === 'idle' || plan.status === 'generating') {
          void watch('supplement', plan.supplementPlanId, false);
        }
      }

      setHydrating(false);
    })();

    return () => {
      active = false;
    };
  }, [watch]);

  const generate = useCallback(
    async (kind: PlanKind) => {
      // A second tap while a plan is being built should do nothing at all: the
      // server would return the same in-flight plan, and restarting the poll
      // here would only leave two loops racing to write the same state.
      if (polling.current[kind]) return;

      setPhase(kind, () => ({ status: 'generating', error: null }));

      try {
        const started =
          kind === 'meal'
            ? await planningService.generateMealPlan()
            : await planningService.generateSupplementPlan();

        const planId =
          'mealPlanId' in started ? started.mealPlanId : started.supplementPlanId;

        await watch(kind, planId, started.status === 'ready');
      } catch (error) {
        if (!mounted.current) return;
        setPhase(kind, (current) => ({
          status: current.data ? 'ready' : 'failed',
          error: messageOf(error),
        }));
      }
    },
    [watch, setPhase],
  );

  const refresh = useCallback(
    async (kind: PlanKind) => {
      try {
        const plan =
          kind === 'meal'
            ? await planningService.getCurrentMealPlan()
            : await planningService.getCurrentSupplementPlan();

        if (plan) store(kind, plan);
      } catch (error) {
        if (!mounted.current) return;
        setPhase(kind, (current) => ({ status: current.status, error: messageOf(error) }));
      }
    },
    [store, setPhase],
  );

  const reset = useCallback((kind: PlanKind) => {
    // Any wait in flight is for a plan built from inputs that no longer apply.
    polling.current[kind]?.abort();
    polling.current[kind] = null;
    if (kind === 'meal') setMeal(IDLE);
    else setSupplement(IDLE);
  }, []);

  const applyMealPlan = useCallback((plan: MealPlan) => {
    setMeal(stateOf(plan));
  }, []);

  const value = useMemo(
    () => ({ meal, supplement, hydrating, generate, refresh, reset, applyMealPlan }),
    [meal, supplement, hydrating, generate, refresh, reset, applyMealPlan],
  );

  return <PlanContext.Provider value={value}>{children}</PlanContext.Provider>;
}

/**
 * A fetched plan as screen state.
 *
 * A plan the server reports as `generating` is held with its status intact and
 * no data, so a screen reopened mid-generation shows the progress it is actually
 * in rather than an empty week.
 */
function stateOf<T extends { status: PlanStatus; error: string | null }>(plan: T): PlanState<T> {
  return {
    status: plan.status,
    data: plan.status === 'ready' ? plan : null,
    error: plan.error,
  };
}

export function usePlan() {
  const ctx = useContext(PlanContext);
  if (!ctx) throw new Error('usePlan must be used within a PlanProvider');
  return ctx;
}
